### ISSUE TITLE
Order by modifier warning

### ISSUE THREAD

**Issue by gsf-greece** [ligasgr/intellij-xquery#204] opened 2016-07-14 18:17 UTC
```
for $x in 1 to 10
order by $x
return $x
```

is OK, but 

```
for $x in 1 to 10
order by $x descending
return $x
```

Gives a warning for word descending
https://www.w3.org/TR/xquery/#doc-xquery-OrderModifier

**Comment by ligasgr** [comment] 2016-07-17 14:02
Can you please show a screenshot of how it looks like when you see the "warning"?
I can, temporarily, see an underscore and not marking as a keyword but only until I type in "return $x".
Does it persists also after full expression is typed in?
Can you please also specify the version of the plugin and the IDE?

**Comment by gsf-greece** [comment] 2016-07-17 14:17
I'm using IntelliJ IDEA 2016.1.3 on Windows 10
XQuery Plugin 3.0.2
The warning persists. 
Example 1 (including some more issues)
![forligas](https://cloud.githubusercontent.com/assets/6191600/16901113/401a0fac-4c42-11e6-8f8a-111802bba209.PNG)
Example 2
![forligas2](https://cloud.githubusercontent.com/assets/6191600/16901115/449d2582-4c42-11e6-9069-04bca3e13736.PNG)

**Comment by gsf-greece** [comment] 2016-07-17 14:22
OK I start to have the feeling It's my fault for using wrong command order... but it still works like that in BaseX so it was confusing. Sorry about false flag :)

**Comment by ligasgr** [comment] 2016-07-17 15:12
You're absolutely right that it should support. It's part of 3.0 version that it can be in any order.
https://www.w3.org/TR/xquery-30/#prod-xquery30-IntermediateClause

The issue is with the lexical analysis aspect where the "where" is missing in the list of "following" tokens (XQuery.flex:285 and XQuery.flex:283).

**Comment by ligasgr** [comment] 2016-07-17 15:14
Thanks for quick response and additional data. It's nearly impossible to analyse the issue without that 👍

**Closed** 2017-01-21 21:12 UTC
Labels: bug, S
